title: "Out of the Box Plugins"

repository: outoftheboxplugins/CleanProject-docs

remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"
logo: "/branding/logo.png"
favicon_ico: "/branding/favicon.ico"

aux_links:
  "Open an issue":
    - "//github.com/outoftheboxplugins/docs/issues"
aux_links_new_tab: true

enable_copy_code_button: true

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

#plugins:
#  - jekyll-seo-tag